name: Unit and integration tests

on:
  push:
    branches:
      - development
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Install dependencies and start jest
      run: npm install && npx jest

    - name: Run unit tests
      run: npm test

    - name: Run integration tests
      run: npm run itest
